### ISSUE TITLE
Option to run a command when a cargo command succeeds

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#13]
Since I'm using `cargo-limit` to populate my quickfix buffer, it would be nice to clear it when a command completes successfully.

I was thinking something along the lines of being able to do `export CARGO_OPEN_SUCCESS=true`, which would cause cargo-limit to run `CARGO_OPEN` even when there are no errors, in which case it would be passed no arguments.

**Comment by alopatindev** [comment]
Is it still actual or it's possible to solve this with [custom open handler](https://github.com/alopatindev/cargo-limit/blob/master/EDITOR-INTEGRATION.md#custom-open-handler) now?

**Comment by casey** [comment]
I haven't checked it out yet, but does the custom open handler get invoked even when there are no errors or warnings?

**Comment by alopatindev** [comment]
> does the custom open handler get invoked even when there are no errors or warnings?

Nope, not yet. Can you populate quickfix list from the custom handler?

**Comment by alopatindev** [comment]
Oh, I guess I got you. I'll add this behavior now.

**Comment by alopatindev** [comment]
Done, the handler runs after success with empty files list.
