### ISSUE TITLE
Allow customizing neovim plugin behavior

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#15]
This is in response to your comment in #12, regarding the the new plugin which `cargo-limit` will invoke via `_cargo-limit-open-in-nvim`.

It would be nice if it were possible to have the plugin optionally invoke a user-defined function instead of navigating to the error locations.

I'm not sure what the best way to configure this would be, but one option would be that if the user has a function called `CargoLimitOpen`, the cargo limit nvim plugin will call that function with the parsed JSON object, instead of jumping to the error locations.

This would let me write a function that would populate the quickfix list, without needing to write a shell script or custom binary that `cargo-limit` invokes. (Which is what I'm currently doing, see https://github.com/casey/dotfiles/blob/master/pkg/nvim-remote-quickfix/src/main.rs)

**Comment by alopatindev** [comment]
Thanks, done.

Please create pull request with your custom function instead of this [poor example](https://github.com/alopatindev/cargo-limit/blob/master/EDITOR-INTEGRATION.md#custom-open-handler), so more users could benefit from it.
