### ISSUE TITLE
Error message  when running cargo limit without neovim

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#19]
I'm switching over to `_cargo-limit-open-in-nvim`, and I'm getting errors when I run `cargo lcheck` without having an `nvim` instance open.

<img width="375" alt="Screen Shot 2021-10-02 at 1 43 00 PM" src="https://user-images.githubusercontent.com/1945/135731244-82ba3343-7354-4ca5-9a37-a7cb08494209.png">

These errors don't occur if I have an `nvim` instance open, which makes me suspect that `cargo-limit` is trying to open the neovim server socket when it doesn't exist.

**Comment by alopatindev** [comment]
Fixed, please run `cargo install nvim-send`
