### ISSUE TITLE
Neovim integration: Is there a way to open the file in a buffer instead of a tab?

### ISSUE THREAD

**Issue by paulrouget** [alopatindev/cargo-limit#27]

**Comment by alopatindev** [comment]
Great question! It's possible by adding a [custom open handler](https://github.com/alopatindev/cargo-limit/blob/376a12f4937c9dc136bb8b242fc6c07064f6db66/EDITOR-INTEGRATION.md#custom-open-handler) to `init.vim`.

This one has identical behavior to opening files in new or existing tabs, but instead it uses buffers:
```viml
function! g:CargoLimitOpen(editor_data)
  let l:initial_file = resolve(expand('%:p'))
  if l:initial_file != '' && !filereadable(l:initial_file)
    return
  endif
  for source_file in reverse(a:editor_data.files)
    let l:path = fnameescape(source_file.path)
    if mode() == 'n' && &l:modified == 0
      execute 'edit ' . l:path
      call cursor((source_file.line), (source_file.column))
    else
      break
    endif
  endfor
endfunction
```

Feel free to reopen the issue if this doesn't solve it for you.

**Comment by paulrouget** [comment]
This is perfect! Thank you! I love this plugin :D
