### ISSUE TITLE
macOS: socket is not recreated after SIGKILLing and restarting nvim

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#43]
I've noticed that sometimes `cargo-limit` doesn't work because the nvim socket is there, but it isn't connected to an nvim instance. It's easy to fix by removing the old socket, but it would be nice if `cargo-limit` (or I guess `nvim-send` in this case) would print an error message when it happens.

**Comment by alopatindev** [comment]
I believe it shouldn't be necessary since I added dead socket removal to nvim plugin (#32).

Does it work for you? I was able to test it on GNU/Linux only, don't know whether it works on macOS.

**Comment by casey** [comment]
I just double-checked, and it looks like it isn't working even after updating. Here's what I did:

- `nvim`
- `cargo ltest` with an error in the code, go-to-error is working
- `kill -9 <NVIM_PID>`
- `nvim`
- `cargo ltest` with the same error, go-to-error isn't working
- Quit `nvim` normally
- `rm -rf /var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/T/nvimFBe1JA` to remove the old socket
- `nvim`
- `cargo ltest` with the same error, go-to-error still isn't working

So for some reason forcibly killing nvim not only breaks the cargo-limit integration, but removing what seems to be the old socket still doesn't help.

I found the socket and tried to interact with it using `nvim-send`, but it didn't work. I tried this:

```
$ echo /var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/*/nvim* /var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/T/nvimE5U4hv
$ nvim-send --servername /var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/T/nvimE5U4hv --remote-send i
```

But the active vim instance didn't enter insert mode as I would expect. So something appears to be wrong, but it doesn't seem to caused by a broken socket lying around.

**Comment by casey** [comment]
Strangely, restarting my computer made it work again.

**Comment by alopatindev** [comment]
> /var/folders/b5/q2c4mxk534v6kwdtx2mpw91m0000gn/T/nvimFBe1JA

It seems to be just a different socket, cargo-limit uses the following kinds of socket paths only: `/tmp/nvim-cargo-limit-${USER}/%escaped%path%to%project%directory`

But anyway, this indeed doesn't look like a correct behavior to me, nvim should recreate the socket if it was restarted after SIGKILL.

Are you using macOS? Thanks.

**Comment by alopatindev** [comment]
For some reason I was sure `ss` command exists on macOS, but I'm most likely wrong. nvim plugin runs it to check whether socket is dead.

What's the output of the following commands on your machine when nvim is running and behaving correctly?

```
time ss --all --listening --family=unix | grep nvim-cargo-limit
```

```
time lsof -U | grep nvim-cargo-limit
```

```
time netstat -a --protocol=unix | grep nvim-cargo-limit
```

Thanks

**Comment by casey** [comment]
> For some reason I was sure `ss` command exists on macOS, but I'm most likely wrong. nvim plugin runs it to check whether socket is dead.

I think that's the issue, `ss` doesn't appear to be installed by default on MacOS:

```
$ time ss --all --listening --family=unix | grep nvim-cargo-limit
zsh: command not found: ss
ss --all --listening --family=unix  0.00s user 0.00s system 45% cpu 0.004 total
grep --color=auto nvim-cargo-limit  0.00s user 0.00s system 69% cpu 0.003 total
```

lsof works:

```
$ time lsof -U | grep nvim-cargo-limit
nvim      46901 rodarmor   30u  unix 0x2e507a035cfbe847      0t0      /tmp/nvim-cargo-limit-rodarmor/%Users%rodarmor%src%just
lsof -U  0.00s user 0.02s system 82% cpu 0.033 total
grep --color=auto nvim-cargo-limit  0.00s user 0.00s system 7% cpu 0.031 total
```

MacOS probably comes with a different version of `netstat` (lots of MacOS utilities are BSD-derived):

```
$ time netstat -a --protocol=unix | grep nvim-cargo-limit
netstat: illegal option -- -
Usage:  netstat [-AaLlnW] [-f address_family | -p protocol]
  netstat [-gilns] [-f address_family]
  netstat -i | -I interface [-w wait] [-abdgRtS]
  netstat -s [-s] [-f address_family | -p protocol] [-w wait]
  netstat -i | -I interface -s [-f address_family | -p protocol]
  netstat -m [-m]
  netstat -r [-Aaln] [-f address_family]
  netstat -rs [-s]

netstat -a --protocol=unix  0.00s user 0.00s system 50% cpu 0.006 total
grep --color=auto nvim-cargo-limit  0.00s user 0.00s system 44% cpu 0.004 total
```

**Comment by alopatindev** [comment]
Thanks! I changed `ss` to `lsof`, hopefully it works as expected now.

**Comment by casey** [comment]
I just updated to the latest version, and that doesn't seem to have worked. After `kill -9 nvim`, go-to-error doesn't work until I manually remove `/tmp/nvim-cargo-limit-rodarmor`.

**Comment by alopatindev** [comment]
Thanks! I hope it should be working now, please update nvim plugin again.

Just in case, if there's still some problem — please try to debug with:
```diff
diff --git a/plugin/cargo-limit.vim b/plugin/cargo-limit.vim
index d68b470..da0e47a 100644
--- a/plugin/cargo-limit.vim
+++ b/plugin/cargo-limit.vim
@@ -137,17 +137,22 @@ function! s:compute_changed_line_numbers()
 endfunction

 function! s:maybe_delete_dead_unix_socket(server_address)
+  set verbosefile=~/.nvim.log
   const lsof_executable = 'lsof'
   const lsof_command = lsof_executable . ' -U'
   if filereadable(a:server_address)
+    call s:log_info('socket_exists')
     call system('which ' . lsof_executable)
     let l:lsof_is_installed = v:shell_error == 0
     if l:lsof_is_installed
+      call s:log_info('lsof_is_installed')
       let l:lsof_stdout = system(lsof_command)
       let l:lsof_succeed = v:shell_error == 0
       if l:lsof_succeed
+        call s:log_info('l:lsof_succeed')
         let l:socket_is_dead = stridx(l:lsof_stdout, a:server_address) == -1
         if l:socket_is_dead
+          call s:log_info('l:socket_is_dead')
           let l:ignore = luaeval('os.remove(_A)', a:server_address)
           call s:log_info('removed dead socket ' . a:server_address)
         endif
```

Debug log is in `~/.nvim.log`, it flushes at least after exiting `nvim`

**Comment by casey** [comment]
Nice, just tested it out and it works. Thank you!
