### ISSUE TITLE
Can't get `CARGO_OPEN` to work

### ISSUE THREAD

**Issue by soenkehahn** [alopatindev/cargo-limit#5]
I'm trying to set `CARGO_OPEN` to have `cargo-limit` execute scripts. But whatever I try I can't seem to manage to make that work.

I have a project with an error in it. `cargo lbuild` shows an error. After doing `export CARGO_OPEN=/usr/bin/echo` I would've expected to see the arguments that `cargo-limit` passes into the `CARGO_OPEN` executable to appear on `stdout`. But I don't see anything. Is this not working anymore? Is there anything else I'm doing wrong?

(I also tried to set `CARGO_OPEN` to a script in the path that would perform other observable side-effects. In case `cargo-limit` swallows the scripts `stdout`. But couldn't get it to execute any scripts. Also, looking at output from [tracetree](https://crates.io/crates/tracetree), i.e. from `tracetree cargo lbuild`, it seems like `cargo-limit` doesn't make an attempt to execute the script in `CARGO_OPEN`.)

**Comment by alopatindev** [comment]
This feature is still not released. Does it work for you with cargo-limit installed [from git](https://github.com/alopatindev/cargo-limit#from-git)?

**Comment by soenkehahn** [comment]
Ah, I see. Yes, on current master this works. Thanks! I'd appreciate a release, then! :)

Also, many thanks for writing `cargo-limit`, it's very handy!
