### ISSUE TITLE
Extra argument passed to binary when using `lrun`

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#6]
Thank you for the great tool!

I think the way that `lrun` works causes extra arguments to be passed to the binary.

I'm doing `cargo lrun foo`, and what's being run is:

```
target/debug/mybin foo --message-format=json-diagnostic-rendered-ansi --
```

I think what's happening is that since `foo` is not a flag, it is causing all following flags to be passed to the binary, instead of to `cargo run`.

**Comment by alopatindev** [comment]
Interesting, thanks. I find weird that this way of passing arguments even works for `cargo run`. Taking into account that this doesn't work:

```
$ cat src/main.rs
fn main() {
    dbg!(std::env::args().collect::<Vec<_>>());
}

$ cargo run -a
error: Found argument '-a' which wasn't expected, or isn't valid in this context

USAGE:
    cargo run [OPTIONS] [--] [args]...

For more information try --help
```
Because here we try to give argument to cargo, not to the program we've written.

This works as expected:
```
$ cargo run -- -a
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/hello -a`
[src/main.rs:2] std::env::args().collect::<Vec<_>>() = [
    "target/debug/hello",
    "-a",
]

cargo run -- a
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/hello a`
[src/main.rs:2] std::env::args().collect::<Vec<_>>() = [
    "target/debug/hello",
    "a",
]

$ cargo lrun -- -a
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/hello -a`
[src/main.rs:2] std::env::args().collect::<Vec<_>>() = [
    "target/debug/hello",
    "-a",
]

$ cargo lrun -- a
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/hello -a`
[src/main.rs:2] std::env::args().collect::<Vec<_>>() = [
    "target/debug/hello",
    "a",
]
```

Probably `cargo run a` is a shortcut to `cargo run -- a`. Or else it's a bug in cargo.

For now as workaround you can do `cargo lrun -- foo`.

**Comment by alopatindev** [comment]
It's surprisingly hard to get correct arguments parser for this wrapper, both writing it by hand and by using clap (which is used in cargo).

I even doubt that it's possible to make clap work correctly for this complicated case. Maybe it's possible, just very hard to configure it properly. And we can't just "copy-paste" existing parsers to get the correct parser in the end, it's not that simple as well.

*Some* of the reasons why the parser is so complex:
- we need to distinguish whether users want to simply run `cargo run` or they for some reason want `cargo run --message-format=something` (which for now I doubt is a common case actually, maybe we shouldn't support it at all)
    - in case of `cargo run` we actually run `cargo run --message-format=json-diagnostic-rendered-ansi` and parse its json output (so we could sort, filter, etc. it)
    - in case of `cargo run --message-format=something` — we actually run what was requested and we don't parse the output
    - we need to be able to at least distinguish cargo's (and its subcommands') arguments from app arguments to do that
        - `cargo run --message-format=json` is not the same as `cargo run -- --message-format=json`
- we need to take into account not only cargo's (and its subcommands') arguments, but also external apps' arguments (like clippy)
    - every app may have its own complicated parsing rules (for instance `cargo run -p CARGO-arg APP-arg` but `cargo run -v APP-arg another-APP-arg` means we need to take into account that `run`'s `-p` has subargument, but `-v` doesn't)
        - also things like `-p=a`
    - any argument can potentially have different meaning for every command/subcommand (for instance `-p` might have subargument for `run` but doesn't have it for something else)
- we need to take into account various color workarounds which also may generate [bugs](https://github.com/alopatindev/cargo-limit/issues/4)
- also surprising cases like this issue, which seems to be a correct clap's parsing feature.

I wish we could simply just use properly configured clap or something similar if that's possible.

For now I don't see a definite good solution. I'll check if it's still possible to do something to at least minimize most common arguments parsing bugs.

**Comment by alopatindev** [comment]
Fixed. Available [from git](https://github.com/alopatindev/cargo-limit#from-git).

**Comment by casey** [comment]
Nice!
