### ISSUE TITLE
Option to disable `cargo-limit is ready` vim message

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#64]
Is there a way to disable the `cargo-limit is ready` message that is printed at the bottom of the screen when cargo limit is ready? Thank you!

**Comment by alopatindev** [comment]
Great idea, I've just added it, please check it
```viml
let g:CargoLimitVerbosity = 2 " warnings level
```

**Comment by casey** [comment]
Awesome, thank you!
